### ISSUE TITLE
possibility to have automatic cleanup on process exit

### ISSUE THREAD

**Issue by omar8792** [tuvistavie/elixir-temp#15]
Hi 
Thanks for this library, i would like to use it to replace the old Briefly library that is no longer manteined.
But The major difference that i found is that is impossibile to auto clean up temp files and folders when process exits like Briefly do.
What do you think about ? 

Thanks

**Comment by danhper** [comment]
Hi,
This is discussed here.
https://github.com/danhper/elixir-temp/issues/10
Help is very welcome!
