### ISSUE TITLE
UTF8 Support

### ISSUE THREAD

**Issue by seemsindie** [tuvistavie/elixir-temp#17]
Hello, I just wanted to ask if there is a utf8 support? Like you would do using File.open/2

```
File.open("myfile.xml", [:write, :utf8])
```

Right now I am getting this error:
```
Erlang error: :no_translation
```

**Comment by nulian** [comment]
Bit old topic but you can pass `mode: [:write, :utf8]` to the Temp.open function.

**Comment by danhper** [comment]
Thanks for sharing. Hopefully, this should do the trick so I'll close this issue.
