### ISSUE TITLE
Documentation does not make it clear which functions cause tracking

### ISSUE THREAD

**Issue by Will-W** [tuvistavie/elixir-temp#19]
`Temp.path()` doesn't result in a file being tracked, unlike `Temp.open()`. This isn't clear from the documentation.

An alternative approach would be to make `Temp.path` track so that it's all consistent. I'm happy to prepare a pull request for either of these options.

**Comment by danhper** [comment]
Thanks for the comment. This is indeed not very clear. I would probably avoid having `Temp.path` track as the intent of the caller is unclear.
If you could send a PR with an improvement to the documentation it would be great. Thanks!

**Comment by Will-W** [comment]
Pull request PR #20 created.
