### ISSUE TITLE
The Temp.open function doesn't handle binary data

### ISSUE THREAD

**Issue by NatTuck** [tuvistavie/elixir-temp#23]
```
    data = <<255, 0, 255>>
    path = Temp.open!("demo", &IO.write(&1, data))
```

results in

```
** (ErlangError) Erlang error: :no_translation
    (stdlib 3.15) :io.put_chars(#PID<0.241.0>, :unicode, <<255, 0, 255>>)
    (elixir 1.12.0) lib/file.ex:1421: File.open/3
    (temp 0.4.7) lib/temp.ex:108: Temp.open/2
    (temp 0.4.7) lib/temp.ex:127: Temp.open!/2
```

**Comment by EpicOrange** [comment]
Still an issue today.

**Comment by danhper** [comment]
@EpicOrange Happy to accept a PR! Thanks!

**Comment by benknowles** [comment]
Is `IO.binwrite` not what you're looking for? The problem with using `IO.write` is that it expects chardata. `IO.binwrite` would allow you to write raw bytes (iodata) and skip the encoding step.

Example:

```
data = <<255, 0, 255>>
path = Temp.open!("demo", &IO.binwrite(&1, data))
```

Above output file in a hex editor:

![image](https://github.com/user-attachments/assets/6a5abf34-dc8f-4f5b-b8f7-dad2bfbbc9ec)

**Comment by NatTuck** [comment]
That makes sense, and means it's a PEBKAC issue rather than a bug in this module.
